<package format="2"><name>quadrotor_msgs</name><version>0.1.0</version>
<description>Planner command messages.</description><maintainer email="maintainer@example.invalid">Maintainer</maintainer><license>BSD</license>
<buildtool_depend>catkin</buildtool_depend><build_depend>message_generation</build_depend><exec_depend>message_runtime</exec_depend><depend>std_msgs</depend><depend>geometry_msgs</depend></package>
